basePath: /api/v1
definitions:
  github_com_0xMarvell_scissor_pkg_models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  github_com_0xMarvell_scissor_pkg_models.GetURLsResponse:
    properties:
      count:
        type: integer
      success:
        type: boolean
      urls:
        items:
          $ref: '#/definitions/github_com_0xMarvell_scissor_pkg_models.URL'
        type: array
    type: object
  github_com_0xMarvell_scissor_pkg_models.GetUserResponse:
    properties:
      success:
        type: boolean
      user: {}
    type: object
  github_com_0xMarvell_scissor_pkg_models.GetUsersResponse:
    properties:
      count:
        type: integer
      success:
        type: boolean
      users:
        items:
          $ref: '#/definitions/github_com_0xMarvell_scissor_pkg_models.User'
        type: array
    type: object
  github_com_0xMarvell_scissor_pkg_models.LoginRequest:
    properties:
      password:
        example: hero108
        type: string
      username:
        example: linchung
        type: string
    type: object
  github_com_0xMarvell_scissor_pkg_models.LoginResponse:
    properties:
      message:
        example: login successful
        type: string
      success:
        example: true
        type: boolean
    type: object
  github_com_0xMarvell_scissor_pkg_models.LogoutResponse:
    properties:
      message:
        example: ' logout successful'
        type: string
      success:
        example: true
        type: boolean
    type: object
  github_com_0xMarvell_scissor_pkg_models.ShortenResponse:
    properties:
      message:
        example: short url created successfully
        type: string
      short_url:
        example: http://localhost:8080/api/v1/8KKoJCy
        type: string
    type: object
  github_com_0xMarvell_scissor_pkg_models.ShortenURLRequest:
    properties:
      url:
        example: https://google.com
        type: string
    type: object
  github_com_0xMarvell_scissor_pkg_models.SignupRequest:
    properties:
      password:
        example: hero108
        type: string
      username:
        example: linchung
        type: string
    type: object
  github_com_0xMarvell_scissor_pkg_models.SignupResponse:
    properties:
      message:
        type: string
      success:
        type: boolean
      user:
        $ref: '#/definitions/github_com_0xMarvell_scissor_pkg_models.User'
    type: object
  github_com_0xMarvell_scissor_pkg_models.URL:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      original_url:
        description: |-
          The url to be shortened

          required: true
          example: https://google.com/
        type: string
      shortened_url:
        description: |-
          The shortened version of the original url

          required: false
          unique: true
          example: djna7L
        type: string
      updatedAt:
        type: string
      user_id:
        description: |-
          The user ID of the user that created the shortened url

          example: 1
        type: integer
    type: object
  github_com_0xMarvell_scissor_pkg_models.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      updatedAt:
        type: string
      urls:
        description: |-
          The urls created by the user

          required: false
          example: password123
        items:
          $ref: '#/definitions/github_com_0xMarvell_scissor_pkg_models.URL'
        type: array
      username:
        description: |-
          The username of the user

          required: true
          unique: true
          example: john_doe
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: Shorten urls for users
  title: Scissor API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login with user details
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/github_com_0xMarvell_scissor_pkg_models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_0xMarvell_scissor_pkg_models.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_0xMarvell_scissor_pkg_models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_0xMarvell_scissor_pkg_models.ErrorResponse'
      tags:
      - authentication
  /logout:
    get:
      description: Logout of user account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_0xMarvell_scissor_pkg_models.LogoutResponse'
        "400":
          description: Bad Request
      tags:
      - authentication
  /shortener/redirect/{shortURL}:
    get:
      description: Redirect short url to original url
      parameters:
      - description: Short URL
        in: path
        name: shortURL
        required: true
        type: string
      produces:
      - application/json
      responses:
        "301":
          description: Moved Permanently
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_0xMarvell_scissor_pkg_models.ErrorResponse'
      tags:
      - urls
  /shortener/shorten:
    post:
      consumes:
      - application/json
      description: Get original url and created a shortened version
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/github_com_0xMarvell_scissor_pkg_models.ShortenURLRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_0xMarvell_scissor_pkg_models.ShortenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_0xMarvell_scissor_pkg_models.ErrorResponse'
      tags:
      - urls
  /shortener/url/{urlID}:
    delete:
      description: Delete a url by its ID
      parameters:
      - description: Url ID
        in: path
        name: urlID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_0xMarvell_scissor_pkg_models.ErrorResponse'
      tags:
      - urls
  /shortener/urls:
    get:
      description: Retrieve all shortened urls created by each user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_0xMarvell_scissor_pkg_models.GetURLsResponse'
        "404":
          description: Not Found
      tags:
      - urls
  /signup:
    post:
      consumes:
      - application/json
      description: Create a new user with the provided details
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/github_com_0xMarvell_scissor_pkg_models.SignupRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_0xMarvell_scissor_pkg_models.SignupResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_0xMarvell_scissor_pkg_models.ErrorResponse'
      tags:
      - authentication
  /users:
    get:
      description: Retrieve all existing user accounts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_0xMarvell_scissor_pkg_models.GetUsersResponse'
        "404":
          description: Not Found
      tags:
      - users
  /users/profile:
    get:
      description: Retrieve an existing user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_0xMarvell_scissor_pkg_models.GetUserResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_0xMarvell_scissor_pkg_models.ErrorResponse'
        "404":
          description: Not Found
      tags:
      - users
swagger: "2.0"
